# General Applications
- hosts: localhost
  connection: local
  tasks:
    - name: Install Firefox
      import_role:
        name: firefox

    - name: Install Obsidian
      import_role:
        name: obsidian

    

              
        
      