# General Applications
- hosts: localhost
  connection: local
  tasks:
    - name: Install Firefox
      become: true
      dnf:
        name: firefox
        state: latest
    - name: Install Obsidian
      import_role:
        name: obsidian

    

              
        
      