#This dependency was not present in Fedora Asahi Linux
- name: Install ZLib Dependency
  become: true
  dnf:
    name: zlib-devel
    state: latest

- name: Python3 PIP
  become: true
  dnf:
    name: python3-pip
    state: latest

- name: Python3 Github Module
  pip:
    name: github3.py
    state: latest

- name: Get Latest AppImage From Github
  github_release:
    user: obsidianmd
    repo: obsidian-releases
    action: latest_release
  register: Obsidian_Latest

- name: Gather current Obsidian version
  find:
    paths: /usr/share
    patterns: ['Obsidian-[0-9]+\.[0-9]+\.[0-9]+-arm64\.AppImage']
    use_regex: yes
  register: Obsidian_Search

- name: Define Installed Obsidian Version
  when: Obsidian_Search.matched != 0
  set_fact:
    Obsidian_Installed_Version: "{{ Obsidian_Search.files[0].path | regex_search('(?<=Obsidian-)[0-9]+\\.[0-9]+\\.[0-9]+(?=-arm64\\.AppImage)') }}"

- name: Define Remote Obsidian Version
  set_fact:
    Obsidian_Remote_Version: "{{ Obsidian_Latest.tag | regex_search('[0-9]+\\.[0-9]+\\.[0-9]+') }}"

- name: Install Obsidian Version
  when: Obsidian_Search.matched == 0 or Obsidian_Installed_Version is version(Obsidian_Remote_Version, "<")
  block:
    - name: Download Obsidian App Image
      become: true
      get_url:
        url: https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ Obsidian_Remote_Version }}/Obsidian-{{ Obsidian_Remote_Version }}-arm64.AppImage
        dest: "/usr/share/Obsidian-{{ Obsidian_Remote_Version }}-arm64.AppImage"
        force: true
    
    - name: Download Obsidian Icon
      become: true
      copy:
        src: obsidian.png
        dest: /usr/share/pixmaps/obsidian.png

    - name: Set Obsidian App Image as executable
      become: true
      shell: chmod a+x "/usr/share/Obsidian-{{ Obsidian_Remote_Version }}-arm64.AppImage"

    - name: Remove Previous Version
      become: true
      when: Obsidian_Search.matched != 0
      file:
        path: "{{ Obsidian_Search.files[0].path }}"
        state: absent

    - name: Create Desktop Shortcut
      become: true
      copy:
        dest: /usr/share/applications/obsidian.desktop
        content: |
          [Desktop Entry]
          Name=Obsidian
          Comment=Obsidian Vault
          GenericName=Markdown Editor
          Exec=/usr/share/Obsidian-{{ Obsidian_Remote_Version }}-arm64.AppImage
          Icon=obsidian
          Type=Application
          StartupNotify=false
          StartupWMClass=Code
          Categories=TextEditor;
          MimeType=application/x-code-workspace;
          Keywords=obsidian;